{
 "title": "Twtxt",
 "description": "Dashboard for the Job Engine",
 "tags": [
  "dashboard",
  "je"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(twtd_server_info, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(twtd_server_info{job =~ '$job'}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "How long je has been up for",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "dtdurationms",
   "valueName": "current",
   "targets": [
    {
     "expr": "twtd_server_uptime{job=\"$job\", instance=\"$instance\"} / 1e6"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "singlestat",
   "description": "Size of the global feed cache",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "twtd_cache_twts{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Cache Perf",
   "type": "singlestat",
   "description": "Cache Performance (last feed cycle processed time in seconds)",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(twtd_cache_last_processed_seconds{job=\"$job\", instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "CPU Usage (%)",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}[$__range]) * 100)",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Memory Usage",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "Cache/Archive Perf",
   "type": "graph",
   "description": "Cache and Archive perf (such as cache last processing time in seconds and rate of archival)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(twtd_cache_last_processed_seconds{job=\"$job\", instance=\"$instance\"}[$__range])",
     "legendFormat": "cache_update_duration"
    },
    {
     "expr": "increase(twtd_archive_size{job=\"$job\", instance=\"$instance\"}[$__range])",
     "legendFormat": "twts_archived"
    }
   ]
  },
  {
   "title": "DB/Cache Stats",
   "type": "graph",
   "description": "Database / Cache Stats (such as no. of users, feeds, sessions, cache size, etc)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twtd_db_feeds{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "db_feeds"
    },
    {
     "expr": "twtd_db_sessions{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "db_sessions"
    },
    {
     "expr": "twtd_db_users{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "db_users"
    },
    {
     "expr": "twtd_db_tokens{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "db_tokens"
    },
    {
     "expr": "twtd_cache_feeds{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "cached_feeds"
    },
    {
     "expr": "twtd_cache_twts{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "cached_twts"
    },
    {
     "expr": "twtd_feed_sources{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "feed_sources"
    },
    {
     "expr": "twtd_server_sessions{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "server_sessions"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU usage of process",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}[$__range]) * 100)",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory usage of process (resident, virtual)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "vm"
    }
   ]
  },
  {
   "title": "Go Memory",
   "type": "graph",
   "description": "Memory usage as sen by Go runtime",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "heap"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "mcache"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "mspan"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "other"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "stack"
    },
    {
     "expr": "go_memstats_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "sys"
    }
   ]
  },
  {
   "title": "Memory Allocations",
   "type": "graph",
   "description": "Memory allocations (bytes, heap, stack)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "heap"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "stack"
    }
   ]
  },
  {
   "title": "Threads / Goroutines",
   "type": "graph",
   "description": "Active threads / goroutines",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "threads"
    },
    {
     "expr": "go_goroutines{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "description": "Garbage Collection duration",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{job=\"$job\", instance=\"$instance\"} / go_gc_duration_seconds_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", instance=\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", instance=\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}