# https://taskfile.dev

version: '3'

output: 'prefixed'

vars:
  TwtdSvc: twtd 
  TwtdExe: twtd{{exeExt}} 

tasks:
  default:
    cmds:
      - task -l
    silent: true

  twtd:
    desc: run twtd service
    cmds:
      - task: run-twtd 


  build-twtd:
    desc: build twtd service
    deps: [twtd-css,twtd-js,tr-merge]
    cmds:
      - echo "{{.TwtdExe}} building..."
      - go build -v -o {{.TwtdExe}} -ldflags "-w -X {{.Module}}.Version={{.Version}} -X {{.Module}}.Commit={{.Commit}}" cmd/{{.TwtdSvc}}/main.go
      - echo "{{.TwtdExe}} built."
    generates:
      - '{{.TwtdExe}}'
    sources: 
      - '**/*.go'
    method: none
    vars:
      Commit:
        sh: git rev-parse --short HEAD
      Version:
        sh: git describe --abbrev=0
      Module:
        sh: go list
    silent: false

  run-twtd:
    cmds:
      -  ./twtd --cookie-secret abc --magiclink-secret abc --api-signing-key abc -R --debug
    deps: [build-twtd]
    desc: run twtd service
    silent: false

  twtd-css:
    cmds:
      - minify -b -o ./internal/static/css/twtxt.min.css ./internal/static/css/[0-9]*-*.css	
    sources:
      - internal/css/**/*.css
    generates:
      - internal/static/css/twtxt.min.css

  twtd-js:
    cmds:
      - minify -b -o ./internal/static/js/twtxt.min.js ./internal/static/js/[0-9]*-*.js		
    sources:
      - internal/js/**/*.js
    generates:
      - internal/static/js/twtxt.min.js

  tr:
    dir: internal/langs
    cmds:
      - goi18n merge active.*.toml 
    desc: goi18n create

  tr-merge:
    dir: internal/langs
    cmds:
      - goi18n merge active.*.toml translate.*.toml
    desc: goi18n merge

