[ErrorFollowAndValidate]
hash = "sha1-0ba152accd240ca7f4e4116a0b1117bfdebb3ba5"
other = "跟隨 Feed  @<{{.Nick}} {{.URL}}> 出錯: {{.Error}}"

[ErrorFollowingUser]
hash = "sha1-431d16794490a3bb584a8e13faae06e877902831"
other = "跟隨用戶出錯"

[ErrorNickOrURLEmpty]
hash = "sha1-39346eb648d77a1728736407c7ab8eb83c266df1"
other = "呢稱 和 URL 必須指定"

[ErrorSetUser]
hash = "sha1-20ba10642a8bd3a4141e40b98deee101889ee1e1"
other = "跟隨 Feed {{.Nick}}: {{.URL}} 出錯"

[MsgFollowUserSuccess]
hash = "sha1-4633defa720997f5a179070ffe8ebc6264424ecc"
other = "{{.Nick}}: {{.URL}} 跟隨成功"
