[BookmarksNoBookmarks]
hash = "sha1-67d3ef16242b6011a62bccdf9dc15c2a999c5ed6"
other = "还没有任何书签"

[BookmarksNoBookmarksSummary]
hash = "sha1-efc43ea07cd5668c0c829258f87f2b33c8e29222"
other = "还没有书签"

[BookmarksTitle]
hash = "sha1-ca3cddd25bd8f6bc4ce35a262e2e1398541ecf3d"
other = "书签"

[BookmarksUser]
hash = "sha1-825ad45a9df6967dce6f317c2499387b590ebaf1"
other = "<b>{{ .Username }}</b> 的书签"

[BookmarksYou]
hash = "sha1-d266af92cbd1cf42a3ff8d2dbf46fa1924dc7de5"
other = "您的书签"
