[FollowHowToContent]
hash = "sha1-28d94b74e71b2b65f4299219080260f2b556fa95"
other = "需要从另一个客户端导入提要列表吗？使用<a href=\"/import\">导入</a>功能。您还可以在/ <a href=\"/discover\">发现</a>页面上的{{.InstanceName}}实例上找到其他用户（假设他们已发布），或在<a href=\"/feeds\">订阅</a>页面上找到其他外部feed的来源。"
