[ErrorHasUserOrFeed]
hash = "sha1-db844234365b0824c1f33d0f76b7548f2bb866b4"
other = "用戶名 或 Feed 名稱已經存在，請選擇其它名稱！"

[ErrorUsernameExists]
hash = "sha1-a66924d2fc116739aecea8d10e3ff1fe0570b476"
other = "用戶(已刪除)名稱已經存在，請選擇其它名稱！"

[ErrorValidateUsername]
hash = "sha1-c4a43aec4a570bfe3db1ea4b81b58fd2db069d86"
other = "用戶名稱驗證失敗：{{.Error}}"
