---
name: Docker
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: make image
